### ISSUE TITLE
build process faults on man directory

### ISSUE THREAD

**Issue by erezschatz** [deadpixi/sam#10]
Building on Ubuntu, on a regular build, root privileges:

```
...
cp sam.1 "/usr/local/share/man/man1"
cp B "/usr/local/bin"
ln -sf "/usr/local/share/man/man1/sam.1" "/usr/local/share/man/man1/B.1"
ln: failed to access ‘/usr/local/share/man/man1/B.1’: Not a directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `/home/ubuntu/sam/doc'
make: *** [install] Error 2
```

Then, if I do 
```
rm /usr/local/share/man/man1
mkdir -p /usr/local/share/man/man1/B.1
```

And rerun make install, it finishes the process with no hitch

I've attempted the same on CentOS and there wasn't any issue

**Comment by deadpixi** [comment]
Hi @erezschatz 

I just pushed a commit. Please check to see if this solves the issue.

Thanks,
Rob

**Comment by erezschatz** [comment]
It does, however, I've attempted a local install (/home/erez/sam) and noticed there are a couple more of locations that require the same treatment, so I followed your example in the commit:

`diff --git a/sam/Makefile b/sam/Makefile
index d763b6b..438b964 100644
--- a/sam/Makefile
+++ b/sam/Makefile
@@ -75,6 +75,8 @@ nuke: clean
        rm -f sam
 
 install:       sam
+       mkdir -p $(SAMDIR)
+       mkdir -p $(SAMSAVEDIR)
        cp sam $(SAMDIR)/$(RSAMNAME)
        cp samsave $(SAMSAVEDIR)/samsave
        chmod +x $(SAMSAVEDIR)/samsave
`

**Comment by deadpixi** [comment]
@erezschatz Please check with the latest master and see if that fixes this issue. Thanks.

**Comment by deadpixi** [comment]
I'm going to close this out, as I believe it's fixed. Please open a new issue if there's still a problem. Thanks!
