### ISSUE TITLE
fatal error: X11/IntrinsicP.h

### ISSUE THREAD

**Issue by CamTosh** [deadpixi/sam#11]
When I use `make install` 
```
gwin.c:8:28: fatal error: X11/IntrinsicP.h: Aucun fichier ou dossier de ce type
compilation terminated.
<commande interne> : la recette pour la cible « gwin.o » a échouée
```
If you have an idea :)

**Comment by deadpixi** [comment]
Ce fichier see trouve dans le package libXt-devel ou quleque chose de
similaire. Utilisez-vous Linux ou an autre systeme?

(Vous pouvez voir, je n'ai pas parler francais dupuis longuetemps. Merci
pour laissez moi la pratiquer.)

In English: please check that you have the libXt-devel package installed
(or something similarly named). Are you using Linux?

**Comment by CamTosh** [comment]
J'utilise Ubuntu 16/04 mate avec le kernel 4.6.
Gcc est en version 5.4.0.

J'ai installé https://packages.debian.org/jessie/libxt-dev l'installation à fonctionner, il faut que j'arrive à le lancer maintenant.
