### ISSUE TITLE
config.mk: can't disable multiple dot-moving keys following the documented procedure

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#13]
config.mk currently says:

```
# If you want to have keyboard control of dot's position, set the following
# variables to the appropriate ASCII control codes. The default values
# emulate the WordStar diamond. Setting any command to zero disables it.
LINEUP=0x05
LINEDOWN=0x18
CHARLEFT=0x13
CHARRIGHT=0x04
```

If you try to do this to disable more than one of these characters, you'll discover that it doesn't work; the build will fail with an error about duplicate case labels, because these values are all used as `case` labels in `type()` in samterm/main.c, so they must have distinct values. This also means that `#define`ing them all to 0x00 if they're undefined at the top of samterm/main.c won't work; if more than one is undefined, you get the same problem.

I think the simplest solution is to change the documentation (and the default `#define`s) to say that to disable a key, set it to a unique negative number (eg -1, -2, -3, -4). This is a bit of a hack because it takes advantage of how the relevant variables are signed ints instead of unsigned ones, but it's easy.

(One can come up with large scale reconstructive fixes if desired. For instance, perhaps it would make sense to put all of the keyboard mapping handling into libXg instead of having some of it in samterm/main.c. For cursor movement, the various deletions, and so on, libXg would emit abstract keys for the various operations (in the same way it emits composed characters), and only libXg would care about how specific physical keys or key sequences are mapped to those operations. Then 'LINEUP' et al would always be defined in samterm/main.c, and it would be libXg's job to decide what, if anything, would generate LINEUP. This description may not make sense.)

**Comment by deadpixi** [comment]
@siebenmann I've completely reworked the keyboard handling code. Please take a look now, I think you'll like it. Please let me know/close this bug if this fixes your problem. Thanks!

**Comment by siebenmann** [comment]
The reworked keyboard handling is great, and lets me cleanly do several customizations that I've been hacking in up until now. It definitely solves my reported problem. Thank you!
