### ISSUE TITLE
RFE: option for the scroll wheel to scroll just one line at a time

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#14]
Right now the mouse scroll wheel jumps significant amounts of distance. It would be nice if there was an option (either build-time or runtime) to scroll things only one line at a time, as xterm and other terminal emulators do. I personally prefer this sort of scrolling, because sam has no other good way to do it while it already has ways to do larger scroll movements (eg PgUp and PgDown, and the cursor keys with standard key bindings).

I have (hacky) code to do the actual line-forward and line-backwards scrolling in [my sam repo](https://github.com/siebenmann/sam) at the top of samterm/main.c, although it may not be the ideal way to do either direction. Please feel free to adapt it if this feature seems good.

**Comment by deadpixi** [comment]
It's not one-line-at-a-time, but it's a lot less drastic now. Wheel-up is equivalent to a button 1 click in the scroll area, and wheel down to a button 3 click. If this works for you, please close this bug. Thanks!

**Comment by deadpixi** [comment]
@siebenmann I'm going to close this; please re-open if the new wheel scrolling functionality doesn't work for you. Thanks!

**Comment by siebenmann** [comment]
I've now had a chance to test this, and I think this is the wrong implementation approach in general (even beyond the issue that I really do want one-line-at-a-time scrolling for myself). The problem with the current approach is that how far the scrollbars move things is relative to where your mouse is in the scroll bar. Or, more exactly, its vertical position relative to the scroll bar. When you use the scroll wheel, this results in all sorts of oddities. For example, if your mouse pointer is outside the current window (if it's hovering over the command window, for example) the scroll wheel does nothing. And how far the scroll wheel moves things depends on the vertical position of the mouse within the window (and on how big the file is); near the bottom, the scroll wheel moves things by a lot, near the top, by a little.

(One might consider this a feature, but I think it's at least confusing. I suspect that most people are going to expect the scroll wheel to move things by a constant amount regardless of where their mouse pointer is.)

**Comment by deadpixi** [comment]
@siebenmann I see what you're saying. I was going for consistency with sam's traditional scrolling behavior (which is...well, inconsistent). I'm doing some major overhauls to the input handling code; getting line-at-a-time scrolling will be easier to do when that's done. I'll reopen the ticket for tracking purposes now.

**Comment by deadpixi** [comment]
@siebenmann The mouse handling code has been significantly reworked, and scrolling a line at a time is now possible. Additionally, the mouse chords are configurable at compile-time (not just on or off, but arbitrarily bindings of mouse button combinations are possible)!

Be sure to read the notes on config.h.def.

I'll close this issue now; please reopen it if this didn't solve your issue. Thanks again for your help.
