### ISSUE TITLE
c99 required to build

### ISSUE THREAD

**Issue by chneukirchen** [deadpixi/sam#18]
gwin.c contains two C99-style loops, which is not the default for older versions of gcc.

Please add -std=c99 to CFLAGS where required.

**Comment by deadpixi** [comment]
Hi @chneukirchen 

Please check out the latest config.mk.def; it sets the C compiler to use C99. Please let me know if there are any more questions. Thanks.

**Comment by chneukirchen** [comment]
That works too. Thanks!

**Comment by chneukirchen** [comment]
Hm, I think it's not a good fix, since calling c99 will set "strict ansi mode", and then e.g. PATH_MAX is not defined by limits.h...

**Comment by deadpixi** [comment]
Hey @chneukirchen please check if you still have the PATH_MAX problem with the latest master. Take a look at config.mk.def; we make sure to define _POSIX_C_SOURCE with a good value there; that should expose PATH_MAX.

If that's not working for you, please reopen this issue.

**Comment by chneukirchen** [comment]
Sorry, I had an old config.mk laying around. The value is good.
