### ISSUE TITLE
linking fails on osx

### ISSUE THREAD

**Issue by mbucc** [deadpixi/sam#20]
hi, looks like osx has none of the *at flavor.

```
8 warnings generated.
c99 -L/usr/X11R6/lib  rsam.o   -o rsam
Undefined symbols for architecture x86_64:
  "_mkfifoat", referenced from:
      _main in rsam.o
  "_openat", referenced from:
      _main in rsam.o
  "_unlinkat", referenced from:
      _cleanup in rsam.o
      _main in rsam.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by deadpixi** [comment]
Hi @mbucc!

Please try building again with the latest master. I don't have easy access to a Mac OS X box to try it out. I honestly don't know what other issues you're going to run into on Mac OS X, either. If linking works, please close this bug. If other issues crop up, please open a new issue and we'll track all of the Mac OS X building issues there.

Thanks!

**Comment by mbucc** [comment]
Hi @deadpixi, here ya go!

```
cd samterm; /Applications/Xcode.app/Contents/Developer/usr/bin/make
c99 -I../include -D_POSIX_C_SOURCE=200809L -I/usr/X11R6/include -I/usr/X11R6/include/freetype2   -c -o main.o main.c
main.c:42:1: error: 'main' must return 'int'
void
^~~~
int
```

after changing the void to int, and recompiling I got two more, both for undeclared NSIG:

```
c99 -I../include -D_POSIX_C_SOURCE=200809L -I/usr/X11R6/include -I/usr/X11R6/include/freetype2   -c -o unix.o unix.c
In file included from unix.c:11:
/usr/include/signal.h:67:42: error: use of undeclared identifier 'NSIG'
extern __const char *__const sys_signame[NSIG];
```

from these two lines of /usr/include/signal.h:

```
#if !defined(_ANSI_SOURCE) && (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
extern __const char *__const sys_signame[NSIG];
extern __const char *__const sys_siglist[NSIG];
#endif
```

_DARWIN_C_SOURCE is (somehow) defined, so these lines are included.

This is OSX 10.9.5, Mavericks.

Thanks!

**Comment by deadpixi** [comment]
Thanks @mbucc. I've changed the return type of main in samterm in master.

Can you try adding "-D_DARWIN_C_SOURCE" to  CFLAGS in the Makefile in whichever directory (sam/samterm/whatever) is having these problems?

**Comment by mbucc** [comment]
@deadpixi, yup, that fixed it.  sam builds and links, and ./sam opens the expected window.  Thanks!

**Comment by deadpixi** [comment]
@mbucc Thank you. Please let me know if sam does/doesn't work as expected on Mac OS X. I'm going to close this issue now, but please reopen it if you run into any problems.

**Comment by deadpixi** [comment]
@mbucc Please try building with the latest master following the instructions in config.mk.def. Thank you!

**Comment by mbucc** [comment]
@deadpixi, yes it builds.  unfortunately, it now crashes when i open it.  (the -d option works fine.) i'll open another ticket for that.
