### ISSUE TITLE
A couple of minor issues...

### ISSUE THREAD

**Issue by RamKromberg** [deadpixi/sam#21]
In no particular order of significance:
0. When writing samsave ( https://github.com/deadpixi/sam/blob/master/sam/sam.c#L160 ), sam tries being smart and uses the shebang line to circumvent calling sh. Unfortunately, with gnu bash this fails with the following error:
```
bash: ./sam.save: samsave: bad interpreter: No such file or directory
```
I tried using _/usr/bin/env samsave_ which did help a little. Unfortunately, gnu bash doesn't pass more than a single argument so that failed as well.
A simple solution would be to write a more typical /bin/sh shebang. So, instead of:
```
#!samsave './test.txt' $* <<'---./test.txt'
testing123
---./test.txt
```
Sam should just do:
```
#!/bin/sh
samsave './test.txt' $* <<'---./test.txt'
testing 123
---./test.txt
```

1. If you're doing c++ style comments, _gcc -std=c89_ won't work. Also, c99 isn't a standard c compiler name. (https://github.com/deadpixi/sam/blob/master/config.mk.def#L5-L6). 
I think your best bet is to go with _cc -std c99_ or whichever standard you're aiming at and make sure the flags are supported both in clang ( http://clang.llvm.org/docs/UsersManual.html#differences-between-various-standard-modes ) and gcc ( https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html#C-Dialect-Options ).

2. Does _/bin/B_ really need a direct _/bin/pwd_ invocation? Can't it just be _pwd_?

3. Similarly, I don't think _/bin/samsave_ needs to force it's own _PATH_.

4. _xdg-desktop-menu_ isn't part of the base system. Maybe _cp deadpixi-sam.desktop $(DESTDIR)/share/applications_ as a fallback?

5. The way numlock breaks Return and Backspace took me by surprise... Might want to look into that or at least document it somewhere... Since I actually knew both sam and ed beforehand, I started playing around with ctrl+enter and other combinations thinking it's some weird default I'm not familiar with :D Only when I finally tried hitting the numpad enter did I guess by chance numlock must be doing something weird :)

Anyhow, these are the immediate issues I noticed working on packaging _deadpixi-sam_ for Nixpkgs (https://github.com/NixOS/nixpkgs/pull/18305).

Thanks for the updated sam :)

**Comment by deadpixi** [comment]
Hi @RamKromberg!

1. In my defense, "c99" is the [POSIX/SUS-mandated name for a c99-conformant compiler](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/c99.html). That particular part of the standard seems widely ignored, though, for whatever reason...

2. The /bin/pwd thing is old, old code. It probably made sense at the time. Is there any reason to change it? It does avoid any issues if someone has (for some bizarre reason) aliased pwd. Also, eventually, B is getting rewritten to talk via X rather than a FIFO. This is because if you open up multiple instances of sam, they lose control over the FIFO in various fragile ways. Using X to communicate directly with samterm avoids that issue entirely.

3. samsave enforcing its own path is again, old old code. Is having it enforce its own path breaking something, though? I'm happy to change it, but if it ain't broke...

4. The use of xdg-desktop-menu is so that whatever desktop environment you're using or whatever local settings you've got that differ from the standard will get the .desktop file installed where it needs to go. The fallback of reporting that the .desktop file wasn't installed was to let you install it where it needs to go on your system, or not at all if you don't have an XDG-compliant environment. To be honest, it doesn't get you much right now anyway as sam/samterm is so not compliant with the relevant standards that you don't get a lot of usefulness.

5. Hm...I've never noticed the NumLock issue before (I have one of those tenkeyless keyboards, so NumLock is meaningless on my setup). I'll have to figure out what's going on with that. Definitely a bug. I'll get it figured out ASAP. I'm sure it's something silly on my part.

**Comment by RamKromberg** [comment]
1. It's not ignored. Rather, it's over-zealously respected: That is, no compiler successfully conformed to posix c99 so none could claimed that namespace. See: https://gcc.gnu.org/c99status.html & http://clang.llvm.org/compatibility.html#c
Regardless, cc and those flags is the De facto standard so so it's not really something worth debating :D

2. 1. Personally, NixOS doesn't have it in that path.
2. 2. Busybox doesn't always deploys it in a link, just as an alias. 
2. 3. Performance: the builtin pwd does the job so there's no good reason to avoid using it.
But it's really a minor issue so whatever :)

3. Yeah a hard path is mandatory and the current form is broken I'm afraid: https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability
The closest you can get to "something in path" is with _/usr/bin/env foobar_ but you can't path multiple arguments so it won't work in this case.

4. I'm aware but while it's not a problem for nix ( https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/X11/xdg-utils/default.nix ), it's an annoying dependency for Macs and some of the BSDs who won't follow XDG specs or use xdg-open and will break a compile over something they won't even use.
However it's actually more useful then you think. Some file-managers use the mimetypes entry to list optional Open With dialog options when double clicking \ right clicking a file. When the users opts to write "sam" in manually, a .desktop is created in _~/.local/share/applications_ that often conflicts and overrides other file-managers who lack proper guis... Basically everyone has their own little quirks in this space so you're right to force your own _.desktop_.

5. You using a laptop, tenkeyless, or some weird Dvorak were the three top reasons I had in mind when I figured it out. In that order :)
And there's nothing to feel silly about. Just today I pushed a patch to nix's plan9port package over acme's broken ctrl+c\v\x\z since Russ and co. are exclusively using Macs so they only binded the Command key and not the Control key ( https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/plan9port/default.nix#L34-L38 ) :D

Which reminds me, are you going to take any design cues from the plan9 version or are you sticking to the older variation? Cause I have to admit, I'm very much in favor of the plan9 variation:

![https://postimg.org/image/q3h5jqt2j/](https://s17.postimg.io/y8z7hwhbh/screenshot.png)

The text cursor is more legible. The scroll-bar is cleaner looking & wider... Well, it's just looks and taste I suppose... But I had to say something just to get it off my chest :)

**Comment by deadpixi** [comment]
@RamKromberg I'm not going to get the numbering right, so I'm just going to use a list:

* Numlock handling should be fixed. Please try it out and let me know if that's true.

* samsave has been completely removed in favor of simply dynamically writing out a script when we rescue. Should work on any POSIX-y system.

* B uses raw pwd now.

* The default compiler is now gcc -std=c99, though obviously this is changeable.

* Double-check your setup please...there shouldn't be a compile-stopping error if xdg-desktop-menu isn't present; you should just get a printed warning.

* The default look is a little Spartan, but I do like the multicolor support that was added recently. That helps some. I totally agree that the thin-line dot should be made more visible; I'll play around with that. The scroll bars...well...those may change or not. They work well enough now and I kinda like them over the newer Plan 9 ones.

At any rate, samterm is going to get massively rewritten at some point in the future to make better use of the X infrastructure that's there (so we might as well use it) and to remove the Xt dependency. At that point, making modifications should be considerably easier.

With the exception of the visibility of the cursor, if these changes have fixed your problems, please go ahead and close this issue. If not, lemme know what's broken.

Thanks again.

**Comment by RamKromberg** [comment]
Yup the two "big" sam.save and numlock issues are sorted out while the minor packaging inconveniences are gone too :)

The scroll bar stuff is just taste and was really just an afterthought mention so don't go putting off anything on my account ;)

Happy to hear I'm not going blind and the line-dot wasn't just me! I figure it goes back to the 640x480 days so it should be at least twice as thick nowadays? Or maybe it should blink... I only have the usual 1080p/23" so I can't imagine what it must be like to someone with a really high dpi... :D

Anyhow, Thanks for dealing with all these issues and updating sam.
