### ISSUE TITLE
Deadpixi sam should be listed on sam.cat-v.org

### ISSUE THREAD

**Issue by deadpixi** [deadpixi/sam#25]
Anyone know any of the cat-v.org guys? I'd love to see this version of sam listed on their page, since it seems to be getting reasonably popular.

**Comment by erezschatz** [comment]
I sent an email to the 9front mailing list, which I think includes the same guys as those running cat-v.org.

**Comment by deadpixi** [comment]
@erezschatz Awesome, I appreciate it.

**Comment by erezschatz** [comment]
I believe this issue can be closed now, http://sam.cat-v.org/

**Comment by deadpixi** [comment]
@erezschatz Excellent, thank you! I really appreciate it.

**Comment by deadpixi** [comment]
@erezschatz L'shana tova, by the way.
