### ISSUE TITLE
RFE: Better way to handle local changes to commands.h (and chords.h)

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#26]
At the moment, it's relatively painful to maintain local changes to commands.h (and probably chords.h, since it uses the same mechanism). With commands.h.def changing and evolving relatively frequently, one keeps having to re-integrate your own changes into a newly changed upstream version. It would be nice if this was easier.

I have a three-part idea for how to improve this:

* document what I currently believe is the case, which is that the table is searched in order and the first match wins.
* add a new key binding kind, Knormal. Knormal simply does whatever sam would normally do if there was no matching entry in commands.h (and the action is ignored).
* #include a 'local-commands.h' at the start of commands.h, and guarantee that local-commands.h ships empty of bindings (but ready for alterations) and will never be changed (except, at most, for changes to an explanatory comment at the start).

With these three changes, people can freely add bindings to their local-commands.h without colliding with upstream changes to commands.h(.def), and their bindings will always take priority over the standard ones. If they want to remove a standard binding, they redefine the key as Knormal and they're guaranteed it will always do the right thing (and their intentions are explicit, as opposed to having to be deduced from a Kcomposed or Kraw binding that inserts itself).

**Comment by deadpixi** [comment]
@siebenmann The latest code greatly simplifies compile-time configuration (by moving all of it to a single file, config.mk) because all of the other customization is available via the new .samrc mechanism. You can put a .samrc file in your home directory with your keybindings, mouse chords, colors, font configuration, etc.

I promise to keep the format of the .samrc file relatively stable. :)

Please see the documentation in the samrc man page, and the sample samrc file in the doc directory. I'm closing this issue, but please reopen it if you have any questions.

**Comment by siebenmann** [comment]
There doesn't seem to be any way to remove a standard binding for a key in the new samrc stuff. Presumably you can bind it to insert itself, but that's at best clumsy. I think it would be better to support an 'unbind' operation, and also a 'bind to do nothing' one so that people could configure things to eg not insert control characters even if they typed them.

**Comment by deadpixi** [comment]
Hey @siebenmann 

The samrc file now has "unbind" and "unchord" directives to remove any previously defined keybindings or chords for a given pattern. Additionally, key sequences and mouse chords can be bound to the "none" command to perform no action and to the "default" command to do whatever the previous definition of that sequence/chord was.

Please close this issue if this solves your problem. Thanks.

**Comment by siebenmann** [comment]
It looks like "unbind" doesn't quite work completely. If you unbind a defined control key (for example 'unbind C e'), typing Ctrl-e inserts 'e' instead of Ctrl-e.

Actually it looks like this may be a general issue where Ctrl-<whatever> no longer inserts a control character but instead ignores the Ctrl modifier, since it seems to happen for unbound Ctrl-whatever keys as well. My personal view is that this should be at least an option.

**Comment by deadpixi** [comment]
I always hated the accidental insertion of control characters, honestly. That removal was intentional. :) If you want to insert control characters, they can be bound as raw insertions, e.g.:

    bind C e raw 0x05

There's only 32 of them; I can add example bindings if needed.

**Comment by siebenmann** [comment]
My personal view is that it would be less surprising to ignore unbound Ctrl characters than to insert the non-Ctrl version. Also, inserting anything has side effects; if you have a selection, try to hit a Ctrl-<x> character that you think has a relevant effect, and miss, inserting a character here will wipe out the contents of the selection. You can undo this, but.

(I mostly agree with you, especially for the old pre-TTF version of sam. More than once I accidentally inserted a control character without realizing it because the old version showed nothing for characters it didn't have a rendering for.)

**Comment by deadpixi** [comment]
With the new "none" binding they can be bound to do nothing as well, so it won't invalidate the selection, using something like:

    bind C e command none

**Comment by siebenmann** [comment]
I (still) think that it's less surprising to have Ctrl-<char> do nothing than insert <char>, so I think sam should ignore all unbound Ctrl keys by default instead of inserting characters here.

In playing around with this, I found another anomaly; Ctrl-i, Ctrl-j, and Ctrl-m all insert the plain character instead of mapping to the appropriate control character. I know, one can map them by hand in .samrc, but I think they should be mapped by default. Ctrl-I is considered the same as Tab by almost everything, so I think it's surprising for sam to behave otherwise by default.

(Possibly this should be a separate bug by now...)

**Comment by deadpixi** [comment]
Agreed. Let's go ahead and close this issue. Please open a new RFE issue that describes how you think control key bindings should work. If it's what I"m thinking, I think I can get 95% of the way there just by messing with the default rules defined in samrc.c. Thanks!
