### ISSUE TITLE
Chorded mouse paste doesn't ignore mouse movement during the paste

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#27]
If you paste something with chorded mouse buttons (B1+B3 usually), normally what you pasted stays selected afterwards. However, if you happen to move the mouse slightly while you're clicking B3 (or deliberately click-and-hold and then move the mouse), this movement causes the selection to reset itself after the paste. The traditional behavior of chorded paste is that this movement is ignored while the chord is in effect, and I think it's clearly the more useful behavior (especially since it's very easy to have the mouse shift slightly).

There are at least some anomalous things that may be happening with mouse movement during a cut chord (B1+B2), but it's less obviously flawed since the cut is made the moment the second button goes down.

This may also be a sign of a larger issue, which is that right now you can't cancel mouse chords, as they fire the moment the second mouse button goes down. I believe that this isn't acme behavior (although, to my surprise, it is the behavior of the original patches to sam).

**Comment by siebenmann** [comment]
In paying attention to how sam is behaving as I use chords, I've come up with what I suspect is a closely related issue or the same issue: if you chord a cut and then move the mouse afterwards before you release button 1, the selection can jump around. I've come to believe that sam should not move the selection until button 1 is released.

(At least for me, the natural way to do the chords is to hold button 1 down, then click either B2 or B3, then release button 1. This leaves a post-chord window where button 1 is still down but I've logically completed the operation and may jog the mouse slightly just by accident.)

**Comment by deadpixi** [comment]
Hey @siebenmann.

Please check out the latest master; I think it works the way you expect it to now. If so, please close this issue.

Thanks.

**Comment by deadpixi** [comment]
@siebenmann I'm going to go ahead and close this issue; I think it's fixed. Please reopen it if this is still a problem. Thanks!

**Comment by siebenmann** [comment]
Sorry for not getting back to you earlier; I had to test this at work, where I saw this issue most vividly in my normal sam use. sam now appears to behave the way I expect it to and I haven't had any selection shifts on cut or paste.
