### ISSUE TITLE
Backspace on highlighted text should delete text

### ISSUE THREAD

**Issue by erezschatz** [deadpixi/sam#29]
This is part of the "make this like Plan9 sam" department.

In P9 Sam, highlight text via left click, then hit backspace deletes the text (And a character before the highlighted text), so it clears the text, then execute backspace (I'm assuming it sets dot before the highlighted text then executes backspace on dot).

In deadpixi Sam, hitting backspace after highlighting text simply performs the "set dot before highlighted text then execute backspace on dot".

As a workaround, chording a "cut" (left-click highlight, middle-click cut) does the same thing.

**Comment by deadpixi** [comment]
Hey @erezschatz 

Please try the latest code in master, this should work correctly now. I'm going to close this issue; please reopen it if there's still a problem. Thanks!

**Comment by erezschatz** [comment]
Works both locally and through -r
