### ISSUE TITLE
RFE: Ctrl-I and Ctrl-J should behave as Tab and Return 

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#30]
Currently, doing an explicit Ctrl-I or Ctrl-J will insert 'i' and 'j' respectively instead of acting as Tab or Return. This is at least surprising; in most everything else the Ctrl-<x> version is the same as the keyboard key. It's also not how the traditional/original version of sam behaves (in it Ctrl-I and Ctrl-J are equivalent to Tab/Return).

**Comment by deadpixi** [comment]
Hello @siebenmann. Please try the latest master; there are now default bindings for Ctrl-I/J/M that match their traditional meanings. Please close this issue if you consider it solved. Thanks.

**Comment by siebenmann** [comment]
The new bindings for me. Thanks!
