### ISSUE TITLE
RFE/bug: unbound Ctrl-<x> keys should do nothing

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#31]
At the moment, sam interprets an unbound Ctrl-<x> key as the same as <x>. This is not traditional sam behavior (it inserts the Ctrl character) and is likely surprising. If one is going to change the traditional sam behavior, I think a better and less surprising default is to do nothing. People holding down Ctrl presumably expect it to do something different than the regular character, after all.

In a sam environment with an increasing number of Ctrl keys bound to do things, doing nothing by default also has the benefit that if you mis-type a Ctrl key (you aim for Ctrl-y, say, but get Ctrl-t by accident), you don't destroy the current selection by replacing it with whatever normal character you just typed.

**Comment by deadpixi** [comment]
@siebenmann Please check out the new master. Unbound control keys are ignored by default. Please close this issue if you consider this solved. Thanks.

**Comment by siebenmann** [comment]
Your change solves this. Thanks.
