### ISSUE TITLE
dead keys for e.g. keyboard-switching or entering accented characters do not work

### ISSUE THREAD

**Issue by rudolfII** [deadpixi/sam#34]
Hello,

usual way of using dead keys does not work.
What should be interpreted as a dead key gets
shown as a rectangle in the editor.

It's both the case of using (dead) keys for writing
accented characters and e.g. using a key to
switch a keyboard layout (in my case the menu key
by itself).

Ruda

**Comment by deadpixi** [comment]
Hi @rudolfII 

Would you mind checking the latest code in master? I think this may have been fixed. If so, please close this ticket. If not, please let me know.

Thanks for your help in debugging, and my apologies for this taking so long to get looked at!

**Comment by rudolfII** [comment]
Hi,

it seems to not have been fixed.

Moreover, I now noticed that if
1) I run sam from a shell with, say, a US keyboard in operation
2) then, in the shell I issue: 'setxkbmap cz'
3) return to the sam window,
then sam seems to still use the US keyboard.

This is just an observation, I don't understand how this can be
possible...

Ruda

**Comment by deadpixi** [comment]
Hi @rudolfII 

The changing-keyboards-at-runtime thing is a known issue; sam only checks the keyboard layout at startup. The code that deals with the keyboard is decades old, and the correct solution is probably rewriting samterm in a more modern toolkit...I'm thinking I'm going to have to bite the bullet and do so.

For the dead-key issue, when you do a dead-key followed by a letter (for example, grave accent and "a"), do you get *both* the rectangle *and* the accented a, or the rectangle and a with no accent?

Thanks.

**Comment by rudolfII** [comment]
On 4 May 2017 at 16:53, Rob King <notifications@github.com> wrote:
> For the dead-key issue, when you do a dead-key followed by a letter
> (for example, grave accent and "a"), do you get both the rectangle and
> the accented a, or the rectangle and a with no accent?

The latter.
I get a rectangle and 'a' with no accent.

Best regards
Ruda

**Comment by deadpixi** [comment]
Hi @rudolfII 

Please try the latest master and let me know if it works. If it does, please close this ticket. Thank you!

**Comment by rudolfII** [comment]
Hello,

> Please try the latest master and let me know if it works. If it does, please close this ticket. Thank you!

better, but still not there.

I no longer see any rectangles, but some characters cannot be entered.
While, e.g., á can be entered using a dead key, neither ě nor Ě can.

(The hook accent is entered using shift and the same dead key used
for á).

Ruda

**Comment by deadpixi** [comment]
> better, but still not there.

Any progress is good. :)

What keyboard mapping/layout are you using?

**Comment by rudolfII** [comment]
> What keyboard mapping/layout are you using?

setxkbmap cz

This makes the = key a dead key; it followed by 'a' produces á,
shift+it followed by 'e' should produce ě.

Ruda

**Comment by deadpixi** [comment]
Hi @rudolfII 

Please try the latest code in master. I believe the issue is fixed. Please close this issue if so. Thank you.

**Comment by rudolfII** [comment]
It seems to work now.
Thanks.
