### ISSUE TITLE
RFE: Specific command binding for the menu 'write' operation

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#37]
Given the potential issues with `command send w` interacting with incomplete lines in the command window, it would be nice to have a specific command binding for the menu 'write' operation. Possibly some other menu operations should have command bindings as well.

**Comment by deadpixi** [comment]
@siebenmann Please try the latest master. "write", "look", and "search" are all available for binding now. Please close this ticket if everything works for you. Thanks.

**Comment by deadpixi** [comment]
HI @siebenmann 

I'm going to close this ticket; please reopen it if you have any problems.
