### ISSUE TITLE
RFE: `$SAMRC` environment variable or something like it

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#38]
Right now sam always loads `.samrc` from your `$HOME`. There are situations (such as being su'd or sudo'd to another login) where this is inconvenient and it would be nice to be able to load `.samrc` from another fixed location. This would also provide a convenient way of temporarily starting sam without a `.samrc` at all, so you're just using standard bindings and behavior; just run eg `SAMRC=/dev/null sam ....`.

**Comment by deadpixi** [comment]
@siebenmann Please try the latest master, and close this ticket if it works for you. Thanks!

**Comment by deadpixi** [comment]
HI @siebenmann 

I'm going to close this ticket; please reopen it if you have any problems.
