### ISSUE TITLE
rsam Makefile misses a rule (at least on OpenBSD)

### ISSUE THREAD

**Issue by rudolfII** [deadpixi/sam#39]
Hello,

when building on OpenBSD, rsam (as the only program
from the set) is not built. I had to add the line

$(CC) -o rsam rsam.o $(LDFLAGS)

to the Makefile's rule for rsam.

It might be just that the "make" on OpenBSD doesn't know
some implicit rule, but this is simply beyond my knowledge...
(Sorry, if that's the case; still I think the explicit rule does not hurt.)

Thanks,
Ruda

**Comment by deadpixi** [comment]
Sorry, I could've sworn I fixed this already. Fixed now.
