### ISSUE TITLE
strange behaviour of accented letters on OpenBSD

### ISSUE THREAD

**Issue by rudolfII** [deadpixi/sam#40]
Hello,

when on OpenBSD I enter accented letters
and then try to delete them, they stay on
the screen. They disappear on window resize.
It only happens for the accented letters.

Thanks
Ruda

**Comment by deadpixi** [comment]
Hi @rudolfII 

Is it the whole letter that stays on the screen, or just the accent?

**Comment by rudolfII** [comment]
Hi,

> Is it the whole letter that stays on the screen, or just the accent?

it's the whole letter.

Ruda

**Comment by deadpixi** [comment]
Hi @rudolfII 

Please try the latest code. I think this has been fixed.

Please close this issue if it's working for you. Thanks!

**Comment by rudolfII** [comment]
Seems ok now.
Thanks
Ruda
