### ISSUE TITLE
select by double-click followed by a chord cut operation: selection not visible in between

### ISSUE THREAD

**Issue by rudolfII** [deadpixi/sam#42]
Hello,

when one wants to cut a word, one can double-click on the word, not
release the (left) mouse button and press the middle button (chord operation).

However, the word gets (now) visibly selected on button _release_, thus
while the above operation does what one expects, the selection is
not visible before the (chord) cut operation. (C.f. acme.)

Thanks
Ruda

**Comment by deadpixi** [comment]
@rudolfII I think this is fixed in the latest master, thanks to a patch from @ahamidullah. I'm going to close this issue, but please reopen it if the problem persists. Thanks!
