### ISSUE TITLE
could not open command socket: Address already in use

### ISSUE THREAD

**Issue by varmanishant** [deadpixi/sam#51]
I am just opening the sam from command line and I get this error. How do I fix this?

Also is there any documentation on how to issue B from outside sam command interface but in the same machine I will try to figure this out. I am suspecting it is becausing of the above error.

**Comment by deadpixi** [comment]
Hi @varmanishant

That error can happen if the control socket isn't deleted for whatever reason (if sam didn't shut down cleanly, for example).

Please check for a file called "sam.remote*" (where '*' can be anything) in /tmp and your home directory. If that file is there and sam is not running, delete it and the problem should be fixed.

**Comment by varmanishant** [comment]
Works fine. Thanks @deadpixi
