### ISSUE TITLE
When piping a directory to sam via pipe / B the process stalls

### ISSUE THREAD

**Issue by ckeen** [deadpixi/sam#53]
When one does 'B ~/bin' samterm will stall and one can only kill the process.

**Comment by deadpixi** [comment]
Hi @ckeen. 

I'm unable to reproduce the issue here on my machine. Is this B the sam command, or B the external utility? Is this in a remote session via SSH or locally? If remote, are you running B on the local machine or the remote machine?

Thanks for your help in debugging.

**Comment by ckeen** [comment]
This is locally with current experimental HEAD running the 'B' shell script. Alternatively echo 'B /home' > .sam.localhost ...

**Comment by deadpixi** [comment]
Hi @ckeen 

Please try with the latest master HEAD and let me know if you still have the problem. I think I need to retire the experimental branch. Thanks again for your patience.

**Comment by ckeen** [comment]
Ah it seems to be fixed there, sorry for the noise!
