### ISSUE TITLE
Pressing alt gr on azerty keyboard inserts unwanted character

### ISSUE THREAD

**Issue by keedt** [deadpixi/sam#54]
Hello,
Whenever I press the right alt key on my azerty keyboard (the so-called alt greek key), a glyph is inserted, with hexadecimal value "ef b8 83".
When I hold the altgreek key and then type for example the 5 key, a [ is displayed like it should,
so apart from inserting this unwanted glyph, the alt gr is working.
In the attached file, I have pressed the following keys:
- alt gr
- 5, while holding the alt gr, and then releasing both keys
- enter
[altgr.txt](https://github.com/deadpixi/sam/files/967622/altgr.txt)

Thanks,

**Comment by deadpixi** [comment]
Hi @keedt.

Please try the latest code in master. Also, please let me know if you have any problems with the sam-specific key composition mechanism (press and hold left alt, and the press two other keys as described in keyboard(5)).

If this all works, please close this ticket. Thanks for your help in debugging!

**Comment by keedt** [comment]
Works like a charm, also the left alt key composition mechanism.
Thanks for the quick bug fix!

**Comment by deadpixi** [comment]
@keedt I just recently made some more changes to the keyboard handling. Would you mind trying the latest master code and letting me know if it still works the way you expect it to? Thank you!

**Comment by keedt** [comment]
Still works like a charm!

**Comment by deadpixi** [comment]
Awesome, thank you.
