### ISSUE TITLE
I-beam cursor for text selection?

### ISSUE THREAD

**Issue by Screwtapello** [deadpixi/sam#59]
I'm playing with Sam to learn more about minimalist text editing, but one thing that keeps tripping me up is that my text selections wind up off-by-one because I'm not used to selecting text with an arrow pointer.

Would it be possible to make sam switch to the I-beam cursor when it's over a text-window, or is the arrow-pointer supposed to be part of the charm, like the way the cursor keys don't actually move the insertion point by default?

**Comment by deadpixi** [comment]
The arrow is supposed to be evocative of the original cursor shape back on the old Blit terminal.

But you're right, we're modernizing sam a bit here. I went ahead and modified samterm to use the ibeam cursor for text, and the arrow only for menus. Please try the latest master and close this issue if it works for you. Thanks!

**Comment by Screwtapello** [comment]
Looks good to me, thanks!
