### ISSUE TITLE
shortcut to switch back to command window (9front)?

### ISSUE THREAD

**Issue by marttt** [deadpixi/sam#8]
Hi. Would you mind adding a keyboard shortcut for switching back to the command window?
9front has this (ctrl-b) and it's really handy.
I believe the implementation can be seen from here:
https://gist.github.com/tintohill/471ee1ddb50f6d5150cd

Being a computer hobbyist, I unfortunately can't get my own head around the code at this point. But I've been really enjoying your version of sam for several months, so thanks anyhow!

BTW, While searching for the ctrl-b implementation, I also found another interesting extended version of sam:
https://bitbucket.org/rennis250/sam

**Comment by deadpixi** [comment]
Hi there,
  This version of sam has the ability to switch back to the command window using ctrl-k, or whatever COMMANDKEY is defined as in samterm/main.c.

   I'm working on centralizing all of the tunable configuration into a config.h header to make that more easily changed, but the functionality is already in there. :)

   Thanks,
   Rob

**Comment by marttt** [comment]
ah yes, I just noticed it (looking at the man page of one of the forks right after posting the issue :). excellent, many thanks! I just wasn't using the current version, so I apologize. it's really great that you continue to work on this project!

**Comment by marttt** [comment]
ah yes, I just noticed it (looking at the man page of one of the forks right after posting the issue :). excellent, many thanks! I just wasn't using the current version, so I apologize. it's really great that you continue to work on this project!
