### ISSUE TITLE
Scrolling without focus

### ISSUE THREAD

**Issue by chneukirchen** [deadpixi/sam#9]
It would be cool if you could mouse-scroll every window without clicking on it first.

**Comment by deadpixi** [comment]
I would love that as well, but it's going to take some pretty heavy re-working of the mouse handling code. It will happen eventually.

**Comment by deadpixi** [comment]
Hey @chneukirchen !

So it only took messing around in the host-terminal protocol, lots and lots of debugging, and probably some hair loss, but...you can now scroll even non-focused layers. :)

Please check out the latest code. Be sure to read the notes in config.h.def.

I'm going to close this issue; please reopen it if there's still a problem or if you have questions. Thanks.

**Comment by chneukirchen** [comment]
On a quick try, seems to work great!
